Created Dot Product Function
itaditya/Python- pull request #3
Opened 2017-10-13 07:01 UTC by MohammadSharif

Using two python lists this function calculates the dot product, if the lists are not the same size or contain incorrect items an error is returned.

2017-10-13 08:40 UTC, itaditya requested changes
@MohammadSharif, please refactor the code. It would be interesting if you use Functional Programming constructs like map, reduce.

2017-10-14 04:04 UTC, MohammadSharif commented
I've updated the code to work with map and reduce by using lambda functions.

2017-10-16 06:58 UTC, itaditya commented on Maths/dotproduct.py
>          for i in range(0, len(first_list)):
You are calculating via map and reduce in the 13th line then why are you using the for loop to iterate again and again and overwrite the value of dot_product?

2017-10-16 06:59 UTC, itaditya commented on Maths/dotproduct.py
> +        print(dot_product)
Also please return the value of dot_product and not print it inside the function

2017-10-17 18:15 UTC, MohammadSharif commented
Apologies as the for loop slipped my mind, I've removed the loop and added a return instead of a print

2025-07-28 06:07 UTC, closed without merging